### numpy 
NumPy is a core Python library for numerical computing, built for handling large arrays and matrices efficiently. It is significantly faster than Python's built-in lists because it uses optimized C language style storage where actual values are stored at contiguous locations

In [1]:
## importing library
import numpy as np

In [2]:
print(np.__version__)   ## checking numpy version

2.5.2


In [8]:
## creating nd array
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [9]:
# 2d array
l1 = [1,2,3,4]
l2 = [5,6,7,8]
arr2 = np.array([l1,l2])
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [21]:
#3d array
l1 = [1,2,3,4]
l2 = [5,6,7,8]
l3 = [9,10,22,34]

arr3 = np.array([[l1,l2,l3]])
print(arr3)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 22 34]]]


In [22]:
np.ones((2,3))          ## creates an array of ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.zeros((2,3))     ## creates an array of zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.linspace(0,1,5)          ## creates evenly spaced values

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [5]:
np.eye(3)                ## 3*3 Identiy matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.arange(10)          ## creates range of value

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Inspecting Array Properties`

In [11]:
print(arr2.shape , arr3.shape)           ## returns shape (rows,columns)

(2, 4) (1, 3, 4)


In [15]:
print([arr2.ndim] , [arr3.ndim])        ## number of dimensions

[2] [3]


In [16]:
arr3.size    ## total elements

12

In [17]:
arr3.dtype         ## datatype of an array

dtype('int64')

### Array Reshaping 

In [29]:
arr.reshape(5,1)          ## change array shape

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [30]:
arr2.flatten()      ## converts to 1d

array([1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
arr2.ravel()        ## returns flatten array (changes original value)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
arr2.T             ## transpose rows and columns

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [24]:
np.vstack((l1, l2))          ## stacks vertically

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
np.hstack((l1 ,l2))        ## stacks horizontally

array([1, 2, 3, 4, 5, 6, 7, 8])

### Indexing and Slicing

In [34]:
arr[1:3]             ## access elements

array([2, 3])

In [35]:
## in 2d 
arr2[:, 1:3]

array([[2, 3],
       [6, 7]])

In [36]:
## in 3d
arr3[:,:,1:3]

array([[[ 2,  3],
        [ 6,  7],
        [10, 22]]])

In [37]:
## boolean indexing 
arr[arr > 2]     ## filter with condition

array([3, 4, 5])

In [29]:
data = np.array([15 , 22 , 9 , 34 , 18 , 5])

In [30]:
## combining conditions (& for AND , | for OR)
data[(data >= 10) & (data <= 20)]

array([15, 18])

In [32]:
## conditional replacement
np.where(data > 15 , "High" , "Low")

array(['Low', 'High', 'Low', 'High', 'High', 'Low'], dtype='<U4')

### Mathematical Operations

In [33]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [37]:
np.add(a,b)           ## addition
          ## or 
#a + b

array([ 6,  8, 10, 12])

In [38]:
np.subtract(b,a)     ## subtraction
         ## or 
# b - a

array([4, 4, 4, 4])

In [39]:
np.multiply(a,b)       ## multiplication
    ## or 
# a * b

array([ 5, 12, 21, 32])

In [40]:
np.divide(a,b)      ## division
     ## or
# a / b

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [41]:
np.power(a,2)        ## exponention
      ## or 
# a ** 2

array([ 1,  4,  9, 16])

In [42]:
np.sqrt(a)        ## square root

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [46]:
np.dot(l1 , l2)           ## matrix multiplication

np.int64(70)

### Statistical Operations

In [53]:
a = np.array([1,2,3,4])

In [47]:
np.mean(a)      ## mean

np.float64(2.5)

In [48]:
np.median(a)    ## median

np.float64(2.5)

In [49]:
np.sum(a)       ## sum of elements

np.int64(10)

In [50]:
np.min(a)       ## minimum value

np.int64(1)

In [51]:
np.max(a)       ## maximum value

np.int64(4)

In [52]:
np.std(a)        ## Standard deviation

np.float64(1.118033988749895)

In [53]:
np.var(a)       ## Variance

np.float64(1.25)

In [54]:
## Finding indices of min/max

In [55]:
np.argmin(a)      ## flat index of minimum value

np.int64(0)

In [56]:
np.argmax(a)      ## flat index of maximum value

np.int64(3)

### Handling missing data

In [57]:
nan_arr = np.array([10 , 20 , np.nan , 40])

In [59]:
np.isnan(nan_arr)     ## checks nan values

array([False, False,  True, False])

In [61]:
## saf aggregations ingoring NaNs

In [62]:
np.nansum(nan_arr)    

np.float64(70.0)

In [63]:
np.nanmean(nan_arr)

np.float64(23.333333333333332)

### Random number generation

In [71]:
np.random.seed(42)          ## set seed for reproducibility 

In [73]:
np.random.rand(3,3)         ## uniform distribution

array([[0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643]])

In [75]:
np.random.randn(10)     ## standard normal distribution

array([-0.19236096,  0.30154734, -0.03471177, -1.16867804,  1.14282281,
        0.75193303,  0.79103195, -0.90938745,  1.40279431, -1.40185106])

In [77]:
np.random.randint(1 , 100 , size = 5)    ## 5 random int between 1 to 99

array([73, 59, 70, 80, 93], dtype=int32)

In [79]:
np.random.choice(nan_arr , size = 2 , replace = False)    ## random sample

array([40., 10.])

In [81]:
np.random.shuffle(nan_arr)      ## shuffle array in-place
print(nan_arr)

[10. 20. 40. nan]


### Set Operations & Unique Values 

In [82]:
words = np.array(["apple" , "banana" , "apple" , "banana" , "orange"])

In [84]:
np.unique(words)      ## unique elements

array(['apple', 'banana', 'orange'], dtype='<U6')

In [86]:
np.unique(words , return_counts = True )          ## unique elements + frequencies

(array(['apple', 'banana', 'orange'], dtype='<U6'), array([2, 2, 1]))

In [87]:
s1 = np.array([1,2,3,4,5])
s2 = np.array([2,4,5,6,9])

In [89]:
np.intersect1d(s1 , s2)     ## common elements

array([2, 4, 5])

In [90]:
np.setdiff1d(s1 , s2)      ## in s1 but not in s2

array([1, 3])

In [92]:
np.setdiff1d(s2 , s1)      ## in s2 but not in s1

array([6, 9])