### numpy 
NumPy is a core Python library for numerical computing, built for handling large arrays and matrices efficiently. It is significantly faster than Python's built-in lists because it uses optimized C language style storage where actual values are stored at contiguous locations

In [1]:
## importing library
import numpy as np

In [2]:
print(np.__version__)   ## checking numpy version

2.5.2


In [3]:
## creating nd array
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [4]:
# 2d array
l1 = [1,2,3,4]
l2 = [5,6,7,8]
arr2 = np.array([l1,l2])
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
#3d array
l1 = [1,2,3,4]
l2 = [5,6,7,8]
l3 = [9,10,22,34]

arr3 = np.array([[l1,l2,l3]])
print(arr3)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 22 34]]]


In [6]:
print(arr2.shape , arr3.shape)           ## returns shape (rows,columns)

(2, 4) (1, 3, 4)


In [7]:
print([arr2.ndim] , [arr3.ndim])        ## number of dimensions

[2] [3]


In [8]:
arr3.size    ## total elements

12

In [9]:
arr3.dtype         ## datatype of an array

dtype('int64')

In [10]:
np.zeros((2,3))     ## creates an array of zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((2,3))          ## creates an array of ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.arange(10)          ## creates range of value

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.linspace(0,1,5)          ## creates evenly spaced values

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## arrray reshaping 

In [14]:
arr.reshape(5,1)          ## change array shape

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [15]:
arr2.flatten()      ## converts to 1d

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
arr2.ravel()        ## returns flatten array (changes original value)

array([1, 2, 3, 4, 5, 6, 7, 8])

## indexing and slicing

In [17]:
arr[1:3]             ## access elements

array([2, 3])

In [18]:
## in 2d 
arr2[:, 1:3]

array([[2, 3],
       [6, 7]])

In [19]:
## in 3d
arr3[:,:,1:3]

array([[[ 2,  3],
        [ 6,  7],
        [10, 22]]])

In [20]:
## boolean indexing 
arr[arr > 2]     ## filter with condition

array([3, 4, 5])

## Mathematical Operations

In [21]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [22]:
np.add(a,b)           ## addition

array([ 6,  8, 10, 12])

In [23]:
np.subtract(b,a)     ## subtraction

array([4, 4, 4, 4])

In [24]:
np.multiply(a,b)       ## multiplication

array([ 5, 12, 21, 32])

In [25]:
np.divide(a,b)      ## division

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [26]:
np.power(a,2)        ## exponention

array([ 1,  4,  9, 16])

In [27]:
np.sqrt(a)        ## square root

array([1.        , 1.41421356, 1.73205081, 2.        ])

### Statistical Operations

In [28]:
a = np.array([1,2,3,4])

In [29]:
print(np.mean(a))      ## mean
print(np.median(a))    ## median
print(np.sum(a))       ## sum of elements
print(np.min(a))       ## minimum value
print(np.max(a))       ## maximum value

2.5
2.5
10
1
4
